### PR TITLE
500 merge-bs-5.3 no color updates or opt into new features yet

### PR DESCRIPTION
**Pull request by garza-utsa**
sorry for the start/stopping, my repo was behind main and was unable to get the latest and greatest merged, finally got it working, I think...

### CODE REVIEW

**Comment by garza-utsa** [comment]
please review locally, or via the GitHub actions PR link once it's ready.  Looking for any large breakages.

For local instances, this does require a fresh install of npm dependencies via: `npm i`

**Review by prd409-utsa — APPROVED** [review]

**Review by lalov1 — COMMENTED** [review]
Everything seems fine, but I'm seeing this weird red border on the preview. I don't see this on the local copy, so I'm unsure what is causing this. Is anyone else seeing this? 

Screenshot 2024-02-22 at 4 56 04 PM

**Comment by Uri-E** [comment]
Hmm... odd, I see the border too. It's like a default border around the html page element in the frame.

**Comment by garza-utsa** [comment]
let me merge in changes from main and see if the new generated PR has the outline, I'm not seeing it locally

**Pull request merged**
