### PR TITLE
Updated labels to comply with accessibility standards

### PR DESCRIPTION
**Pull request by prd409-utsa**
Updated labels to comply with accessibility standards example included with this issue description.

### CODE REVIEW

**Review by lalov1 — COMMENTED** [review]
Looks good! Some of the `for` and `id` attributes are a mix of dashes or camelCase for their naming conventions. I'm not sure if we should standardize or if there are already classes styling them. Also, should we add the `name` attribute to form fields? I don't think it's required for form fields.

**Comment by garza-utsa** [comment]
standardization would be good, even if we have to fix up the sass a bit.  We aren't heavily using these form elements yet in production, so I don't mind getting a little crazy with the cleanup.

**Review by garza-utsa — CHANGES_REQUESTED** [review]
one big change, let's standardize to lowercase hyphenated for all attributes.  I do see a lot of camelCase and lowercase and even some hyphenated mixed in

**Comment by prd409-utsa** [comment]
labels and ids are now all lowercase hyphens. name= has been removed from all inputs.

**Review by garza-utsa — APPROVED** [review]
👍

**Pull request merged**
