### PR TITLE
Sprint 02 cta button and cta button image

### PR DESCRIPTION
**Pull request by garza-utsa**

### CODE REVIEW

**Comment by prd409** [comment]
Just looking at this... is seems the Blue and Orange buttons are not matched up to their correct category? 
Screen Shot 2022-01-09 at 7 42 45 PM
Screen Shot 2022-01-09 at 7 44 35 PM

**Comment by prd409** [comment]
Oh...I see. It's the background color, not the actual button color. :)

**Comment by garza-utsa** [comment]
@prd409 it was weird, {{ path image}} didn't work at first until I restarted fractal (control +c and then npm run start again)

**Comment by garza-utsa** [comment]
think I fixed the margin issues on the orange bg/blue buttons (it's really nice having permalink to preview each component/variant):

https://utsa-asc.github.io/college-dls/sprint-02-cta-button/components/preview/call-to-action-image--orange-2up.html

**Comment by prd409** [comment]
Looks great!

**Pull request merged**
