### PR TITLE
adding more specific anchor styles for .highlight-card-link

### PR DESCRIPTION
**Pull request by garza-utsa**
- also adding some more real world examples from new future site

### CODE REVIEW

**Review by Uri-E — COMMENTED** [review]
i don't know if it's just me, but the image isn't showing up...

Other than that it looks gewd, lolz

**Review by lalov1 — COMMENTED** [review]
Should we change the hover on the button, so it isn't orange on orange? 

Also, the hover padding for the title looks a little off: 
Screen Shot 2022-07-22 at 4 52 54 PM
Screen Shot 2022-07-22 at 4 53 11 PM

**Comment by garza-utsa** [comment]
drats, I did not test hover on all of them...I'll move some of the images from 3rd party URLs to the local images folder

**Review by lalov1 — COMMENTED** [review]
images don't seem to work for me, but everything else looks good.
Screen Shot 2022-07-25 at 11 29 15 AM

**Comment by garza-utsa** [comment]
hmm, I'll move the data into a config as a separate branch

**Pull request merged**
