### PR TITLE
782 dls striped table with a th on a row doesnt meet color contrast standards

### PR DESCRIPTION
**Pull request by garza-utsa**
adjusting colors for striped grey and blue to $white-b background and $blue for th elements, addresses #782

### CODE REVIEW

**Review by lalov1 — APPROVED** [review]
👍🏽

**Review by Uri-E — COMMENTED** [review]
Colors and text looks good, but I'm seeing two bold 'Row One's on the tables now. The CSS or HBS data needs to be adjusted.

**Comment by garza-utsa** [comment]
yeah, I added a <th> to the first two rows to replicate the issue on https://housing.utsa.edu/resources/dates-deadlines.html

**Review by Uri-E — APPROVED** [review]
Ah, OK. Then party on, dudes.

**Pull request merged**
