### PR TITLE
added color:  for paragraph and sidebar text

### PR DESCRIPTION
**Pull request by prd409-utsa**

### CODE REVIEW

**Comment by garza-utsa** [comment]
@prd409-utsa  still seeing the email link disappear when switching to dark mode

**Comment by garza-utsa** [comment]
Screenshot 2024-05-28 at 11 50 03 AM

**Comment by prd409-utsa** [comment]
@garza-utsa scss updated to make the email link visible. Ready for review again.

**Review by garza-utsa — APPROVED** [review]
👍

**Pull request merged**
