### PR TITLE
691: removed component 05-faculty-group

### PR DESCRIPTION
**Pull request by prd409-utsa**
Removed components / 03-sections / 05-faculty-group. 

Renamed: 05-profile-group, 06-link-list, and 07-faculty-slider

### CODE REVIEW

**Review by lalov1 — CHANGES_REQUESTED** [review]
Errors on the following pages: 
- https://utsa-asc.github.io/college-dls/691-dls-remove-duplicate-component/components/detail/department-home-page.html
- https://utsa-asc.github.io/college-dls/691-dls-remove-duplicate-component/components/detail/department-secondary-page--default.html
- https://utsa-asc.github.io/college-dls/691-dls-remove-duplicate-component/components/detail/department-secondary-page--landing-2.html

Also, I'm unsure if the rollup changes should be in this PR.

**Review by garza-utsa — CHANGES_REQUESTED** [review]
see comments from @lalov1  on the errors on other pages, most likely the render calls need to be updated to the new names.

also, move the rollup changes to a different pull request, we do not add js dependencies to the repo

**Comment by garza-utsa** [comment]
the PR included a top level folder "rollup-plugin-replace", I think you can safely delete this one

**Review by garza-utsa — APPROVED** [review]

**Review by lalov1 — APPROVED** [review]
👍🏽

**Pull request merged**
