### PR TITLE
544 dls contact callout wicons

### PR DESCRIPTION
**Pull request by lalov1**
Please let me know your thoughts. I was wondering if it should be part of the content callout section, but it seems different. Also, open to color and layout suggestions.

### CODE REVIEW

**Comment by garza-utsa** [comment]
These look great, only red flags I see are the regular blue text against the light blue back ground (Default) and the blue heading against the orange background (Orange), please double check the contrast on these, otherwise, I think they are good to go

**Review by garza-utsa — APPROVED** [review]
👍

**Comment by lalov1** [comment]
> nvm, just double checked them and they are above 3.4 ^^b

I ran them with the WAVE tool and had no errors as well.

**Review by Uri-E — APPROVED** [review]
Looks gewd! 

I think the col classes might need to get more descriptive so the icons stack on mobile screens tho

**Pull request merged**
