### PR TITLE
Hid all information in a singular accordion

### PR DESCRIPTION
**Pull request by lalov1**

### CODE REVIEW

**Comment by prd409-utsa** [comment]
@lalov1  The accordions are working as expected and it looks good.  But I noticed 3 empty accordions at the bottom of the page. Are those supposed to be there?
Screen Shot 2022-09-12 at 2 11 51 PM

**Comment by lalov1** [comment]
> @lalov1 The accordions are working as expected and it looks good. But I noticed 3 empty accordions at the bottom of the page. Are those supposed to be there? Screen Shot 2022-09-12 at 2 11 51 PM

Yes, they should have the same information as the accordion component: 
https://utsa-asc.github.io/college-dls/faculty-profile-to-unordered-list/components/detail/accordion.html

I could delete them if it's too confusing.

**Comment by prd409-utsa** [comment]
No, that's fine. Just checking.

**Review by prd409-utsa — APPROVED** [review]

**Review by garza-utsa — APPROVED** [review]
👍

**Pull request merged**
