### PR TITLE
adding default bootstrap behavior for dropdown links without the styling

### PR DESCRIPTION
**Pull request by garza-utsa**
conforms to the normal dropdown behavior, but removes the icon styling since we have our own plus sign toggle

### CODE REVIEW

**Comment by prd409-utsa** [comment]
As far as clicking anywhere on the button and the dropdown expanding it works perfectly.  But I noticed the toggle +  only switches to - if you click directly on the +. 
Here's. screenshot of it expanded from when I clicked on Admission Requirements.
Screen Shot 2022-09-12 at 6 26 37 PM

**Comment by prd409-utsa** [comment]
This is page I was using: https://utsa-asc.github.io/college-dls/454-cms-right-nav-links-with-secondary-page-links/components/detail/department-home-page.html

**Comment by prd409-utsa** [comment]
Oh, and the background hover #dbdee3. only stays selected if you click the words. If you click the icon the background stays the same transparent. So either or for that result, but not two different background results depending on what/where you click..

**Review by prd409-utsa — CHANGES_REQUESTED** [review]
Left comments on the main page of the pull requests. About two different experiences results, depending on where you click on the button: words vs icon toggle.

**Comment by garza-utsa** [comment]
ah, nice catch, may need adjusting in the script.js

**Comment by garza-utsa** [comment]
readjusted the semantics for this sidemenu, will need to be adjusting inside CAS as well, breaking html change for sidemenu @jampafoo

**Pull request merged**
