### PR TITLE
570 dls add back to top indicator

### PR DESCRIPTION
**Pull request by lalov1**
I could do it without JS, but let me know what y'all think. Also, housing has a chat that might conflict with this.

### CODE REVIEW

**Review by prd409-utsa — CHANGES_REQUESTED** [review]
I don't see anything in the DLS for back to top.  Should there be a button or link?...or something...? 
[https://utsa-asc.github.io/college-dls/570-dls-add-back-to-top-indicator/components/detail/back-to-top.html](https://utsa-asc.github.io/college-dls/570-dls-add-back-to-top-indicator/components/detail/back-to-top.html)
Also, the documentation says Site-Footer
Screen Shot 2023-11-05 at 9 16 37 AM

**Comment by garza-utsa** [comment]
it's always showing for me on safari, even in the component page, by default

**Comment by lalov1** [comment]
> it's always showing for me on safari, even in the component page, by default

I added a commit to the component page for it to show, causing the reference pages to flicker a little. This isn't an accurate representation of what will happen once it goes live.

**Comment by lalov1** [comment]
> I lik it! Looks like it's working fine to me (on chrome). Could we fiddle with the delay once you click on the BtT button tho? I think it should be faster, almost immediate even.

I removed the delay. Let me know if that looks better.

**Review by Uri-E — APPROVED** [review]

**Comment by Uri-E** [comment]
Looks gewd. You steam a good ham.

**Comment by garza-utsa** [comment]
can we have an alternate variant for placement on the left? I noticed a couple of DLS sites use the right bottom for chat/bot windows.

I'm open to either, but should the js live in the college-dls-bundle?  Or is it better to keep it out with the element?  It's a fairly small snippet, but if this becomes standard on all pages, may make more sense to have it live inside the bundle

- housing.utsa.edu
Screenshot 2023-11-06 at 10 28 56 AM

- future.utsa.edu
Screenshot 2023-11-06 at 10 29 08 AM

**Pull request merged**
