### PR TITLE
Created 500 internal error page. CSS animation works fine here in DLS.

### PR DESCRIPTION
**Pull request by prd409-utsa**
Please review. No issues with getting this to work in repo. So not sure what could be causing the problems with its functionality when added directly to a page in Cascade DLS.

### CODE REVIEW

**Review by lalov1 — APPROVED** [review]
Hopefully, it works in Cascade now. It might be nice to have a way for the person to report the error or how they're getting to the page.

**Comment by garza-utsa** [comment]
would CAS be stripping the inline <style> tags maybe?  Worth testing this build on WALLEDEV to see if that's the case, does indeed work fine:

https://utsa-asc.github.io/college-dls/554-500-server-error-page/components/preview/internal-error-page.html

**Review by Uri-E — APPROVED** [review]
Looks like it's working fine for me. I like it! It's cooky and fun.

**Comment by garza-utsa** [comment]
> Hopefully, it works in Cascade now. It might be nice to have a way for the person to report the error or how they're getting to the page.

In our college sites, lets make sure to add a new WYSIWYG section row after this to let college communicators have a spot to let people know who to reach out to for help

**Review by garza-utsa — COMMENTED** [review]
👍

**Pull request merged**
