### PR TITLE
adding compact variant

### PR DESCRIPTION
**Pull request by garza-utsa**
4-up profile group variant, only change needed was to adjust the hardcoded min-height for the image.  Also putting all the profile-card-list css into this component (profile-group) scss file instead of in the smaller organism profile-card

### CODE REVIEW

**Comment by garza-utsa** [comment]
this is for issue #629

**Review by prd409-utsa — APPROVED** [review]
I edited in browser to add a 4th card. Before it was the big ol' email address that ran outside the container. But looks good now. Great work!
Screenshot with 4-up:
screencapture-utsa-asc-github-io-college-dls-components-preview-faculty-group-html-2023-10-25-14_36_10

**Review by prd409-utsa — CHANGES_REQUESTED** [review]
Changed my review status ater putting in a longer email name. See my previous comment about long email addresses

**Review by lalov1 — APPROVED** [review]
👍🏽

**Comment by garza-utsa** [comment]
is there a snazzy css text-break property we can use to always break super-long-non-spaced-content-so-that-it-doesn't-overflow-like-that?

**Comment by prd409-utsa** [comment]
> is there a snazzy css text-break property we can use to always break super-long-non-spaced-content-so-that-it-doesn't-overflow-like-that?

word-wrap: break-word;

**Comment by garza-utsa** [comment]
added break-word to .profile-card definition, also had to remove a display:inline from the component

**Review by prd409-utsa — APPROVED** [review]

**Review by Uri-E — APPROVED** [review]

**Pull request merged**
