### PR TITLE
339-fix-typos: second PR for this

### PR DESCRIPTION
**Pull request by prd409-utsa**
closeicon to close-icon
breacdrumb to breadcrumb
informations to information
productedBy to produced-by
grouph to group
reserach to research
borad to board
sbtitle to subtitle
Ancheor to Anchor
Ttile to Title
Staf to Staff
Studeies to Studies
scnd to second
deoartment to department
positio_abs to position-absolute
Siderbar to Sidebar
faculity to faculty
lrpad to lr-pad

In image names and their links: 
managment to management, 
statisstics to statistics

That's all I could find so I think this TASK is finished.

### CODE REVIEW

**Comment by prd409-utsa** [comment]
Thanks for fixing the stuff you commented on in first PR, @garza.

**Comment by prd409-utsa** [comment]
Also, I think we should back-bill Simpson Scarborough $20 for each typo and $5 for every instance of that typo.  We would get back a significant amount of funds.

It is disgraceful they delivered this, in my opinion.

**Comment by prd409-utsa** [comment]
Just finished this up today so I wouldn't think about it constantly and ruin my weekend. :)

**Review by lalov1 — APPROVED** [review]
Thank you for doing all the edits!

**Review by Uri-E — APPROVED** [review]
Awesome possum!

**Pull request merged**
