### PR TITLE
376 dls sidebar removal of heading

### PR DESCRIPTION
**Pull request by garza-utsa**
@Uri-E, this was last week when we discussed this item in particular, but let me know if the styling on the first list item is enough.  Made the weight heavier and increase the font size slightly.

### CODE REVIEW

**Review by lalov1 — APPROVED** [review]
Looks good! 👍🏽

**Review by Uri-E — APPROVED** [review]
I lik it!

**Comment by garza-utsa** [comment]
@Uri-E, I'm going to attach this to a unique class as future wants to keep this styling the same for all list item, I'll also attempt to address issue #400

**Comment by garza-utsa** [comment]
- moving first item styling to the .heading class, removed old .heading styles
- adding a variant with the heading class applied
- brought in the example orientation page as a testing variant to make sure the first item bug when it's a dropdown issue was fixed

**Pull request merged**
