### PR TITLE
I added a class for accordions to show on print

### PR DESCRIPTION
**Pull request by lalov1**
I added a class, but I thought about adding the following scss:
`	@media print{
		.collapse {
			display: block !important;
			height: auto !important;
		}
		.accordion-button:after {
			content: " ";
			color: $white;
		}		
	}`

Let me know when y'all think.

### CODE REVIEW

**Comment by prd409-utsa** [comment]
When I tried to print, it looks like it's adding an addtional collapsed accordion between the ones with content...or does that **+** belong to the active accordions?

Here's PDF of what I'm seeing in Print mode.
[accordion-print-preview.pdf](https://github.com/utsa-asc/college-dls/files/13417258/accordion-print-preview.pdf)

**Comment by garza-utsa** [comment]
did you know you can emulate print mode in chrome?
https://developer.chrome.com/docs/devtools/rendering/

**Comment by lalov1** [comment]
> did you know you can emulate print mode in chrome? (I didn't) https://developer.chrome.com/docs/devtools/rendering/

I didn't know that either, but you could also render dark and light mode there.

**Comment by lalov1** [comment]
> When I tried to print, it looks like it's adding an addtional collapsed accordion between the ones with content...or does that **+** belong to the active accordions?

This belongs to the other accordions

> 
> Here's PDF of what I'm seeing in Print mode. [accordion-print-preview.pdf](https://github.com/utsa-asc/college-dls/files/13417258/accordion-print-preview.pdf)

I don't know why there are considerable gaps in the print mode, but the Chrome print render looks fine.

**Review by prd409-utsa — APPROVED** [review]

**Review by Uri-E — APPROVED** [review]
Seems to be working OK for me.

**Pull request merged**
